### ISSUE TITLE
404 on npm package

### ISSUE THREAD

**Issue by aleksUIX** [nickmccurdy/karma-edge-launcher#12]
Hello,

I tried to use your edge launcher and got a 404 on the npm package install. Am I doing something wrong or is it not available anymore?

Thanks,
Aleks

**Comment by nickserv** [comment]
Sorry for the delay, this isn't published yet. I haven't had much time to do enough troubleshooting for a stable release, but please let me know if you are interested in contributing.

**Comment by marcoscaceres** [comment]
Let me know if there is anything I can do to help. Please ping me for code review, etc. Would like to use this.

**Comment by nickserv** [comment]
I added a note to the readme. This should make it clear that it's not on npm yet, but feel free to send an issue or pull request if you want me to change the wording.

**Comment by nickserv** [comment]
This is now on npm, see the readme.
