### ISSUE TITLE
Use the Edge Diagnostics Adapter

### ISSUE THREAD

**Issue by nickserv** [nickmccurdy/karma-edge-launcher#14]
Microsoft just released the [Edge Diagnostics Adapter](https://github.com/Microsoft/edge-diagnostics-adapter) for debugging Edge. Since it's tricky to launch Edge as a modern-style app (and there are still bugs on master currently), I'm going to try switching to this adapter.

If this is fixed, not much else will block this launcher from being published.

**Comment by auchenberg** [comment]
Our Edge Diagnostics Adapter doesn't use special launch functionality for Edge, so unless you need to use the debugging capabilities of the adaptor, I recommend you keeping this karma launcher by using alternative packages like: https://github.com/MicrosoftEdge/edge-launch or https://github.com/MicrosoftEdge/MicrosoftEdgeLauncher

**Comment by nickserv** [comment]
Thanks for the feedback, I didn't realize that this was primarily meant for debugging and that there was another launcher that used an exe file. I'll probably switch to using [MicrosoftEdgeLauncher](https://github.com/MicrosoftEdge/MicrosoftEdgeLauncher).

**Comment by nickserv** [comment]
@auchenberg It seems like `edge-launch` is using a similar command to launch Edge, and I'm running into an issue where Karma thinks that Edge crashes because the process (powershell) technically closes after Edge launches. I would like to use `MicrosoftEdgeLauncher` to get around this, but I can't think of a more idiomatic way to require it than committing a binary to this repository (which would make updating this repository more complicated). Do you have any recommendations?

**Comment by auchenberg** [comment]
Our `MicrosoftEdgeLauncher` is simply a C++ wrapper for running the command `open microsoft-edge:<url>`, which you simply could run from node via `spawn`

That should solve the powershell specific problem.

**Comment by nickserv** [comment]
The issue I'm having is that Karma wants the launcher be defined as shell commands (as an array of strings), and it expects the first process to be the browser itself.

**Comment by jacobrossi** [comment]
I don't know if there's a way to launch via a shell command directly.  @thejohnjansen @instylevii do you know?

**Comment by andysterland** [comment]
Unfortunately modern apps, including Edge, are not directly launched the same way exes are with CreateProcess instead the shell activates (launches) them more like a local COM server. Which in Edge is further complicated as tabs are typically spawned in a separate process, a child app container, today that's tricky to handle as there isn't realy a way to follow it like a typical [child process created event](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681423%28v=vs.85%29.aspx). Indeed even Visual Studio has no real support for debugging child app containers :(. 

With regards to shell commands your options are fairly limited. If Edge is the default browser it's easy and you can just trigger an open command on a URL and Windows will launch Edge. Otherwise you have to use the microsoft-edge protocol handler. I.e.:
`explorer.exe microsoft-edge:http://bing.com`
Or use some other app that's installed to launch the app. 

But if you want to watch the duration of the launched page that won't help. Indeed I'm not sure what would help there. Hopefully @thejohnjansen or @instylevii have some magic :). 

Fwiw the `MicrosoftEdgeLauncher` also wouldn't help in this case as the launcher will exit as soon as it launches Edge. I was looking at changing that behavior and hack something, terrible, that enables it to follow the lifetime of the child process. But no plans yet.

**Comment by instylevii** [comment]
The supported and public method I know of for launching modern apps like Edge is:
https://msdn.microsoft.com/en-us/library/windows/desktop/hh706902(v=vs.85).aspx

**Comment by andysterland** [comment]
@InstyleVII It is, that and any protocol handlers etc. But, alas, you can't call `IApplicationActivationManager::ActivateApplication` directly from the shell. The MicrosoftEdgeLauncher used that approach originally but I believe it doesn't work for `file://` URLs :(. 

@nicolasmccurdy  do you need to track the lifetime of the page that's being opened?

**Comment by marcoscaceres** [comment]
@andysterland @jacobrossi, can't emphasize enough how critical it is to get this working (for us poor saps on non-windows systems!). I'm super excited to see you guys here and hope we can get this resolved soon so we can use it to test W3C spec generation (see https://github.com/w3c/respec/issues/723).

**Comment by marcoscaceres** [comment]
@auchenberg, @andysterland, @InstyleVII, @jacobrossi, friendly ping... ❤️

**Comment by instylevii** [comment]
Just chatted with a dev and it looks like you can launch it using this command:
`explorer.exe shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge`

You can get the name of the Edge folder from running the powershell command below:
`get-appxpackage *microsoftedge*`

Which will return:
`Name              : Microsoft.MicrosoftEdge
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : Neutral
ResourceId        :
Version           : 38.14351.1000.0
PackageFullName   : Microsoft.MicrosoftEdge_38.14351.1000.0_neutral__8wekyb3d8bbwe
InstallLocation   : C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.MicrosoftEdge_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False`

If you take the PackageFamilyName that's part of the value, then append !MicrosoftEdge that should get you the command on a per-machine basis (I think the license will be the same though but can't guarantee).

Note that this will actually launch an entire new instance of Edge in regards to the frame (not just a new tab if you have one open) but will still share session state with any open instances of Edge. I'll play around with it more and see what's possible.

**Comment by andysterland** [comment]
@marcoscaceres 

Could you clarify your requirements as there's a couple of options and knowing what you need would help pick.
1. Can you include a binary (or npm package) in your launcher?
2. Do you need to launch Edge at URL passed as a command line argument? 
3. Does that URL need to only support `http(s)` or do you need to support `file://` uri?
4. Do you need to monitor the lifetime of the tab that is launched? (so you can keep something alive that is watching it.)

**Comment by marcoscaceres** [comment]
> Can you include a binary (or npm package) in your launcher?

Yes. In fact, prefer an npm package so we can automatically have it updated. 

> Do you need to launch Edge at URL passed as a command line argument?

Yes. 

> Does that URL need to only support http(s) or do you need to support file:// uri?

http(s). We have various things pointing to absolute URLs, so they would get tripped up by file:// as the origin.  

> Do you need to monitor the lifetime of the tab that is launched? (so you can keep something alive that is watching it.)

Yes. Karma, the testing framework, manages the spawned process. It communicates with the tab via Web Sockets.  

You can see our setup here:
https://github.com/w3c/respec

For CI, we are relying on [appveyor](https://www.appveyor.com). For example:
https://ci.appveyor.com/project/marcoscaceres/respec/build/248

And we are using Travis also:
https://travis-ci.org/w3c/respec/builds/131877171

Ideally, we want to have Appveyor look exactly the same as our Travis output above.

**Comment by FeodorFitsner** [comment]
How can I help you guys?

**Comment by marcoscaceres** [comment]
@FeodorFitsner, thanks for joining the discussion on behalf of AppVeyor! We are trying to get Karma to run MS Edge on Windows-based CI solutions like AppVeyor. At this point, we are just trying to see if it's possible to get Edge to simply launch a URL from the command line (and be controlled as a NodeJS process). Ultimately, we will need your help to make sure that Edge can be spun up and run on AppVeyor's VMs. Your thoughts, comments, etc. throughout this process would be invaluable.

**Comment by FeodorFitsner** [comment]
AppVeyor VMs have Windows Server 2012 R2, but Edge is for Windows 10 only, no?

**Comment by marcoscaceres** [comment]
oh... 😢

**Comment by andysterland** [comment]
@marcoscaceres I've started to take a look at changing the MicrosoftEdgeLauncher to follow the lifetime of the launched tab. The work in progress is over at: https://github.com/MicrosoftEdge/MicrosoftEdgeLauncher/compare/addKeepalive?expand=1 
If I get working I'll also bundle it up and put it up on NPM.

@FeodorFitsner Edge is also on Windows Server 2016, if that works for you? If not happy to help.

**Comment by marcoscaceres** [comment]
@andysterland, thanks for the update! I've subscribed to the repo.

**Comment by FeodorFitsner** [comment]
Providing Windows Server 2016 is more realistic. We'll start rolling it out which its license has "go live" status. Alternatively, we are working on support of "custom build clouds" for the next release of AppVeyor, so you can add your own Azure Subscription and run builds there.

**Comment by nickserv** [comment]
I started using @andysterland's keepalive flag for Microsoft Edge Launcher and it seems to keep the launching process open consistently. My work in progress can be seen in #19, and I'll probably replace this PR with that one.

**Comment by nickserv** [comment]
I'm using [edge-launcher](https://github.com/MicrosoftEdge/edge-launcher) instead.
