### ISSUE TITLE
Fail plugin path resolution

### ISSUE THREAD

**Issue by falsandtru** [nickmccurdy/karma-edge-launcher#18]
```
02 08 2016 14:00:34.568:ERROR [plugin]: Cannot find plugin "...\node_modules/karma-edge-launcher".
  Did you forget to install it?
  npm install ...\node_modules/karma-edge-launcher --save-dev
```

**Comment by nickserv** [comment]
What is this error from? I'm assuming you were trying to install this by name through npm. Unfortunately, this plugin isn't stable yet as I haven't had much time to work on it and update it for Windows 10's stable release, so I purposely avoided publishing it to npm.

If you want to try the currently development version (which might not work at all), you can give npm the address of this git repository. If you would like to contribute to help make this stable or you are familiar with Windows development and have suggestions, feel free to leave a comment or PR.

**Comment by nickserv** [comment]
Actually, I just noticed that someone else seems to have published a package with the same name, though I'm not sure if it's working. Please post the command and/or source code that got you this error message.

**Comment by falsandtru** [comment]
Sorry, I installed by npm. Its source is not here. Thanks for your kindness.

**Comment by nickserv** [comment]
Yeah, I think you're looking for https://github.com/watilde/karma-edge-launcher. If that package works for you and is stable, let me know and I will deprecate this one.

**Comment by falsandtru** [comment]
I tried to use that plugin, but it does not work. Unfortunately, also your plugin does not work correctly. It has hung and does not close an edge browser after the test is finished. Now I don't know which is a cause that my product, edge, or your plugin.

https://github.com/falsandtru/spica

```
$ gulp test
(node:17184) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[06:07:39] Using gulpfile ...\spica\gulpfile.js
[06:07:39] Starting 'clean'...
[06:07:39] Finished 'clean' after 19 ms
[06:07:39] Starting 'test'...
[06:07:39] Starting 'ts:test'...
[06:07:52] Finished 'ts:test' after 13 s
[06:08:11] Starting 'karma:test'...
DEPRECATED: use your own version of lodash, this will go away in karma@2.0
03 08 2016 06:08:33.911:INFO [karma]: Karma v1.1.2 server started at http://localhost:9876/
03 08 2016 06:08:33.915:INFO [launcher]: Launching browsers Chrome, Firefox, Edge with unlimited concurrency
03 08 2016 06:08:33.938:INFO [launcher]: Starting browser Chrome
03 08 2016 06:08:34.010:INFO [launcher]: Starting browser Firefox
03 08 2016 06:08:34.381:INFO [launcher]: Starting browser Edge
03 08 2016 06:08:36.493:INFO [Chrome 51.0.2704 (Windows 10 0.0.0)]: Connected on socket /#P6GyEbeb05qSmp0WAAAA with id 32514520
03 08 2016 06:08:39.193:ERROR [launcher]: Cannot start Edge

03 08 2016 06:08:39.204:INFO [launcher]: Trying to start Edge again (1/2).
03 08 2016 06:08:40.375:INFO [Edge 13.10586.0 (Windows 10 0.0.0)]: Connected on socket /#34yNSa1WSI8n9-anAAAB with id 10869596
03 08 2016 06:08:41.755:ERROR [launcher]: Edge crashed.

03 08 2016 06:08:41.759:INFO [launcher]: Trying to start Edge again (2/2).
........................
Chrome 51.0.2704 (Windows 10 0.0.0) LOG: 'lib/fingerprint', 851110613
................................................................03 08 2016 06:08:44.429:ERROR [launcher]: Cannot start Edge

03 08 2016 06:08:44.433:ERROR [launcher]: Edge failed 2 times (cannot start). Giving up.
....
Chrome 51.0.2704 (Windows 10 0.0.0) LOG: 'lib/uuid', 'e89b7003-1dd7-48fd-a804-188567dc2c61'
Chrome 51.0.2704 (Windows 10 0.0.0) LOG: 'lib/uuid', 'e7da9857-9332-4d69-8c71-96b3d01a6a97'
Chrome 51.0.2704 (Windows 10 0.0.0) LOG: 'lib/uuid', 'e860311e-ac70-4d48-9b88-c87ca28fe660'
................................................................................
................................................................................
................................................................................
......
Chrome 51.0.2704 (Windows 10 0.0.0): Executed 333 of 333 SUCCESS (2.054 secs / 1.504 secs)
...........03 08 2016 06:08:51.586:INFO [Firefox 47.0.0 (Windows 10 0.0.0)]: Connected on socket /#9Nf29iCcRF3kWSJ9AAAC with id 31799841
.......
Edge 13.10586.0 (Windows 10 0.0.0) LOG: 'lib/fingerprint', 393756163
....................................................
Firefox 47.0.0 (Windows 10 0.0.0) LOG: 'lib/fingerprint', 275227720
....................................................................
Firefox 47.0.0 (Windows 10 0.0.0) LOG: 'lib/uuid', '35f6a961-3145-483b-8367-c4f22cb2aa02'
Firefox 47.0.0 (Windows 10 0.0.0) LOG: 'lib/uuid', 'e68030f9-30d8-4c51-8603-287fef5fc3f2'
Firefox 47.0.0 (Windows 10 0.0.0) LOG: 'lib/uuid', '473be860-65a4-465a-b77d-abd93472d337'
................................................................................
................................................................................
................................................................................
...........
Firefox 47.0.0 (Windows 10 0.0.0): Executed 333 of 333 SUCCESS (2.835 secs / 1.05 secs)
TOTAL: 727 SUCCESS
[06:09:10] 'karma:test' errored after 59 s
[06:09:12] Error: 1
    at formatError (...\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (...\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (...\spica\node_modules\orchestrator\index.js:264:8)
    at ...\spica\node_modules\orchestrator\index.js:275:23
    at finish (...\spica\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (...\spica\node_modules\orchestrator\lib\runTask.js:29:3)
    at Timeout.removeAllListeners [as _onTimeout] (...\spica\node_modules\karma\lib\server.js:379:7)
    at tryOnTimeout (timers.js:228:11)
    at Timer.listOnTimeout (timers.js:202:5)
[06:09:12] Finished 'test' after 1.53 min
```

**Comment by nickserv** [comment]
I haven't tried that other plugin, but I am aware that my plugin fails to close Edge properly. I was using a special shell command to launch Edge, but unfortunately the command finishes by the time Edge starts, so the calling code doesn't realize that Edge is still running since it thinks the command that closed was Edge itself. However, if you ignore these failures it should still run the tests.

**Comment by falsandtru** [comment]
I see, thanks for your advice.

**Comment by nickserv** [comment]
I now have this package released on npm as `karma-edge-launcher` (versions 0.1+). If you don't mind, could you check if your tests still fail on the latest version? I haven't noticed anything in my basic testing beyond the closing issue, but I also haven't used this in a more production-sized project yet.

**Comment by falsandtru** [comment]
Thanks. But I cannot finish my tests at the single run. In the following repo, `gulp watch` works well, but `gulp test` hang own process.

https://github.com/falsandtru/spica

**Comment by nickserv** [comment]
I just tried it locally, and the launcher eventually causes Edge to crash/hang which eventually disconnects and fails the tests. It's also odd that Edge opened two tabs instead of one, if I remember correctly edge-launcher might have problems keeping multiple pages open (especially if Edge was already open).

We can make a new issue to track this if you want, but I'm not sure exactly what's causing it yet.

**Comment by falsandtru** [comment]
Thanks for the repro. I'll open a new issue.
