### ISSUE TITLE
How to use on CI?

### ISSUE THREAD

**Issue by dotnetCarpenter** [nickmccurdy/karma-edge-launcher#34]
I'm trying to use `karma-edge-launcher` to run [our test suite](https://ci.appveyor.com/project/dotnetCarpenter/svg-js) on appveyor, but I get `ERROR: The process "MicrosoftEdge.exe" not found.`.

But I don't know how to install [**MicrosoftEdge.exe**](https://github.com/MicrosoftEdge/edge-launcher) from appveyor's PowerShell.

[`ps: Install-Product "MicrosoftEdge.exe" appveyor`](https://www.google.com/#q=ps:+Install-Product+%22MicrosoftEdge.exe%22+appveyor&*) on google gives me nothing.

This would be great information to have in the *README*.

**Comment by dotnetCarpenter** [comment]
Perhaps a joint effort, using [#22 on edge-launcher](https://github.com/MicrosoftEdge/edge-launcher/issues/22) is worth pursuing?

**Comment by nickserv** [comment]
karma-edge-launcher does depend on edge-launcher. It's supposed to install and find the exe automatically. I'm not sure if this is a bug in my package or an issue with edge-launcher being outdated or having a broken package.

**Comment by dotnetCarpenter** [comment]
I'm on Ubuntu Linux and don't have access to a Windows box. The path when installing `edge-launcher` look good. I'm thinking that appveyor doesn't respect my appveyor.yml which dictates `os: Visual Studio 2015`.

I'll create a support question.

**Comment by nickserv** [comment]
If I remember correctly, appveyor still doesn't have Edge. Because this depends on edge-launcher which also depends on Edge (it does not bundle an executable for the browser itself), you can't use it on appveyor. The path you noticed in edge-launcher is probably the path to its launcher binary, which isn't the path of the Edge browser.

The good news is that the edge-launcher npm package is now up to date (see https://github.com/MicrosoftEdge/edge-launcher/issues/22), and you can use a different CI service like Sauce Labs or anything that has Edge installed in a Windows environment. However, you have a good point that this should be documented. I don't have a ton of experience using this on CI services myself, but I'd be happy to aggregate information into the readme or take pull requests for it. Also, please let me know if appveyor support got back to you, or if you found another option that's working for you.

**Comment by dotnetCarpenter** [comment]
@nickmccurdy You are right about appveyor. They don't and probably won't support MS Edge for a long time since their infrastructure is based on Windows Server and even the newest version, Windows Server 2016, does not support MS Edge.

[As MS notes](https://technet.microsoft.com/en-us/itpro/microsoft-edge/hardware-and-software-requirements):
> The Long-Term Servicing Branch (LTSB) versions of Windows, including Windows Server 2016, don't include Microsoft Edge or many other Universal Windows Platform (UWP) apps. These apps and their services are frequently updated with new functionality, and can't be supported on systems running the LTSB operating systems. For customers who require the LTSB for specialized devices, we recommend using Internet Explorer 11.

If [we](https://github.com/svgdotjs/) migrate our tests to source labs, I'll write down how I configured *karma-edge-launcher'.

**Comment by nickserv** [comment]
@FeodorFitsner Please let us know if AppVeyor has made progress for builds with Edge or Azure support, or if there is a rough schedule for its support.

**Comment by FeodorFitsner** [comment]
Edge is not available on Windows Server 2016 therefore we can't support it either on our primary build cloud.

**Comment by nickserv** [comment]
Thanks, I am aware that Windows Server 2016 doesn't support it. In https://github.com/nickmccurdy/karma-edge-launcher/issues/14#issuecomment-222275029 you mentioned the possibility of remote builds that could use Azure, and it seemed like a feature like this could help with Edge support.

**Comment by FeodorFitsner** [comment]
@nickmccurdy Yes, this feature is currently available. We plan it for Premium accounts only, but as it's still new we can do an exception.

**Comment by nickserv** [comment]
Great, if you have any documentation pages for the Azure integration in general or something more specific about Edge, I'd be happy to add it to the readme as a recommendation.

**Comment by guruvamsichintala** [comment]
We are running Jenkins CI to run the npm tests( where it launches Chrome, Firefox, Edge and runs the tests). It works when we run the command locally on the machine. But when triggered through Jenkins we get error 

ERROR [launcher]: Cannot start Edge
:INFO [launcher]: Trying to start Edge again (1/2).

Jenkins and jobs are running on Windows 10 machine.

**Comment by nickserv** [comment]
> It works when we run the command locally on the machine.

Just to clarify, have you tried this on the specific machine that you have Jenkins set up on? If not, keep in mind that Windows Server still doesn't have Edge, so it would naturally cause builds to fail.

**Comment by guruvamsichintala** [comment]
I tried running the command  on the specific Jenkins machine locally, it worked. But when I ran through jenkins I see the error 

ERROR [launcher]: Cannot start Edge
:INFO [launcher]: Trying to start Edge again (1/2).

When ran through jenkins, as the output shows cannot start edge but when I check on machine **Edge browser is opened with the url example.com**  And the tests wont run so it fails
